"""password column

Revision ID: 496d1a5f2e0e
Revises: 9d10d5cc78fa
Create Date: 2023-06-03 22:25:44.022365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496d1a5f2e0e'
down_revision = '9d10d5cc78fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
